<Window3@BoxLayout>
    orientation: "vertical"

    ActionBar:
        ActionView:

            ActionPrevious:
                title: 'PinPong Game'
                with_previous: False

            ActionButton:
                text: 'Back'
                on_press: print("change disp window 2"); app.root.change_disp()

    BoxLayout:
        Label:
            text: 'GAME OVER'
            #黄緑
            color: 0,1,0,1

            font_size: 200